### ISSUE TITLE
BIG ASK!!

### ISSUE THREAD

**Issue by tnmdynamiq** [bryalv77/card-slider-like-tinder#1]
Big ask! Would you mind adding an example on codepen or something like that?

**Comment by bryalv77** [comment]
There you go man:

https://codepen.io/bryalv77/pen/JjzxYdK

**Comment by tnmdynamiq** [comment]
> There you go man:
> 
> https://codepen.io/bryalv77/pen/JjzxYdK

Thank you so much for getting back to me so quickly, I appreciate it!
